import React from 'react';

const ReportFooter = () => {
    return (
        <div className="mt-12 mb-8 px-4 text-center border-t border-gray-100 pt-8 no-print">
            <p className="text-gray-400 text-xs sm:text-sm font-sans font-medium">
                Report generated by Direktor.
            </p>
            <p className="text-gray-400/60 text-[10px] sm:text-xs font-sans mt-1">
                Advanced Tournament Management solutions crafted by Emmanuel Enyi.
            </p>
        </div>
    );
};

export default ReportFooter;
