-- Create pending_results table
CREATE TABLE IF NOT EXISTS public.pending_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    tournament_id bigint REFERENCES public.tournaments(id) ON DELETE CASCADE,
    player1_id bigint REFERENCES public.players(id),
    player2_id bigint REFERENCES public.players(id),
    player1_name text,
    player2_name text,
    score1 integer DEFAULT 0,
    score2 integer DEFAULT 0,
    round integer,
    status text DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    submitted_by text -- Optional: IP or user info if we tracked it
);

-- Enable RLS
ALTER TABLE public.pending_results ENABLE ROW LEVEL SECURITY;

-- Allow public insertion (unauthenticated) for remote submission if tournament allows it
-- But typically we might want some basic check or just open it up.
-- For this "event coverage index", it implies public access.
CREATE POLICY "Allow public insert to pending_results"
ON public.pending_results
FOR INSERT
WITH CHECK (true);

-- Allow dashboard users (owner) to view/update/delete
CREATE POLICY "Allow owners to manage pending_results"
ON public.pending_results
USING (
    EXISTS (
        SELECT 1 FROM public.tournaments t
        WHERE t.id = pending_results.tournament_id
        AND t.user_id = auth.uid()
    )
);

-- Add remote_submission_enabled to tournaments
ALTER TABLE public.tournaments 
ADD COLUMN IF NOT EXISTS remote_submission_enabled boolean DEFAULT false;

-- Add submitted_remotely to results to track origen
ALTER TABLE public.results
ADD COLUMN IF NOT EXISTS submitted_remotely boolean DEFAULT false;
