-- Add Glicko-2 parameters to players table for current state tracking
ALTER TABLE public.players 
ADD COLUMN IF NOT EXISTS rating_deviation float DEFAULT 350.0,
ADD COLUMN IF NOT EXISTS volatility float DEFAULT 0.06;

-- Create table to store historical ratings per round
CREATE TABLE IF NOT EXISTS public.round_ratings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    tournament_id bigint references public.tournaments(id) on delete cascade not null,
    round integer not null,
    player_id bigint references public.players(id) on delete cascade not null,
    old_rating float not null,
    new_rating float not null,
    rating_change float not null,
    old_rating_deviation float,
    new_rating_deviation float,
    matches_played integer default 0,
    wins integer default 0
);

-- Add index for fast lookup
CREATE INDEX IF NOT EXISTS idx_round_ratings_tournament_round ON public.round_ratings(tournament_id, round);
CREATE INDEX IF NOT EXISTS idx_round_ratings_player ON public.round_ratings(player_id);

-- Enable RLS
ALTER TABLE public.round_ratings ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON public.round_ratings FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.round_ratings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public.round_ratings FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public.round_ratings FOR DELETE USING (auth.role() = 'authenticated');
